swagger: '2.0'
info:
  description: DM Online Banking
  version: 1.0.0
  title: DM Online Banking
  contact:
    email: u.devillartay@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8080'
basePath: /v1
tags:
  - name: clients
    description: Everything about your Clients
    externalDocs:
      description: Find out more
      url: 'http://localhost:8080'
schemes:
  - http
paths:
  /clients:
    post:
      tags:
        - clients
      summary: Add a new client
      description: ''
      operationId: create
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: UserDto object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Client'
      responses:
        '200':
          description: Ok
    get:
      tags:
        - clients
      summary: Retrieve all clients
      description: ''
      operationId: list
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Client object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Client'
      responses:
        '200':
          description: Ok
  '/clients/{id}':
    put:
      tags:
        - clients
      summary: Update an existing Client
      description: ''
      operationId: update
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          description: Client object that needs to be added to the store
          required: true
      responses:
        '200':
          description: Ok
definitions:
  Client:
    type: object
    required:
      - nom
      - prenom
      - id
    properties:
      id:
        type: integer
        format: int64
      nom:
        type: string
        example: jarnouen de villartay
      prenom:
        type: string
        example: ulysse
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
